//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyzeSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnalyzeSet()
        {
            this.BristleAnalysisResultSets = new HashSet<BristleAnalysisResultSet>();
            this.BrushAnalysisResultSets = new HashSet<BrushAnalysisResultSet>();
            this.TuffAnalysisResultSets = new HashSet<TuffAnalysisResultSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int iSKU_id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Equipament { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BristleAnalysisResultSet> BristleAnalysisResultSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrushAnalysisResultSet> BrushAnalysisResultSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TuffAnalysisResultSet> TuffAnalysisResultSets { get; set; }
    }
}
