//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BristleAnalysisResultSet
    {
        public int Id { get; set; }
        public string DefectClassification { get; set; }
        public string DefectIdentified { get; set; }
        public int Probability { get; set; }
        public bool SelectedManual { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string Position { get; set; }
    
        public virtual AnalyzeSet AnalyzeSet { get; set; }
    }
}
