//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrushAnalysisResultSet
    {
        public int Id { get; set; }
        public int TotalBristles { get; set; }
        public int TotalGoodBristles { get; set; }
        public int TotalBristlesAnalyzed { get; set; }
        public string AnalysisResult { get; set; }
        public bool Hybrid { get; set; }
        public int Signaling_Id { get; set; }
    
        public virtual AnalyzeSet AnalyzeSet { get; set; }
    }
}
