//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Debug
    {
        public int iID { get; set; }
        public string Debug { get; set; }
        public Nullable<System.DateTime> event_time { get; set; }
    }
}
