//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ColgateSkeltaEntities : DbContext
    {
        public ColgateSkeltaEntities(string connString)
            : base()
        {
        }

        public ColgateSkeltaEntities()
            : base ("name=ColgateSkeltaEntities")
        {
        }

        
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalyzeSet> AnalyzeSet { get; set; }
        public virtual DbSet<BristleAnalysisResultSet> BristleAnalysisResultSet { get; set; }
        public virtual DbSet<BristleSet> BristleSet { get; set; }
        public virtual DbSet<BristleTempSetSet> BristleTempSetSet { get; set; }
        public virtual DbSet<BrushAnalysisResultSet> BrushAnalysisResultSet { get; set; }
        public virtual DbSet<DatasetSet> DatasetSet { get; set; }
        public virtual DbSet<ImageSet> ImageSet { get; set; }
        public virtual DbSet<ImageTempSetSet> ImageTempSetSet { get; set; }
        public virtual DbSet<RegistrationWaitingSet> RegistrationWaitingSet { get; set; }
        public virtual DbSet<Sample_ASet> Sample_ASet { get; set; }
        public virtual DbSet<TuffAnalysisResultSet> TuffAnalysisResultSet { get; set; }
        public virtual DbSet<TuftSet> TuftSet { get; set; }
        public virtual DbSet<TuftTempSetSet> TuftTempSetSet { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<ValidationDataset> ValidationDataset { get; set; }
        public virtual DbSet<Vsample_ASet> Vsample_ASet { get; set; }
        public virtual DbSet<VtuftSet> VtuftSet { get; set; }
        public virtual DbSet<VbristleSet> VbristleSet { get; set; }
        public virtual DbSet<VimageSet> VimageSet { get; set; }
        public virtual DbSet<UserSystem> UserSystem { get; set; }
        public virtual DbSet<GeneralSettings> GeneralSettings { get; set; }
        public virtual DbSet<AI_Sample_log> AI_Sample_log { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<QM_Spec> QM_Spec { get; set; }
        public virtual DbSet<SKU> SKU { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Shift> Shift { get; set; }
    
        [DbFunction("ColgateSkeltaEntities", "ngsfr_fn_S_Split_List")]
        public virtual IQueryable<ngsfr_fn_S_Split_List_Result> ngsfr_fn_S_Split_List(string @string)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ngsfr_fn_S_Split_List_Result>("[ColgateSkeltaEntities].[ngsfr_fn_S_Split_List](@string)", stringParameter);
        }         
    }
}
