//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ColgateSkeltaEntities : DbContext
    {
        public ColgateSkeltaEntities()
            : base("name=ColgateSkeltaEntities")
        {
        }        
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnalyzeSet> AnalyzeSet { get; set; }
        public virtual DbSet<BristleAnalysisResultSet> BristleAnalysisResultSet { get; set; }
        public virtual DbSet<BristleSet> BristleSet { get; set; }
        public virtual DbSet<BristleTempSetSet> BristleTempSetSet { get; set; }
        public virtual DbSet<BrushAnalysisResultSet> BrushAnalysisResultSet { get; set; }
        public virtual DbSet<DatasetSet> DatasetSet { get; set; }
        public virtual DbSet<ImageSet> ImageSet { get; set; }
        public virtual DbSet<ImageTempSetSet> ImageTempSetSet { get; set; }
        public virtual DbSet<RegistrationWaitingSet> RegistrationWaitingSet { get; set; }
        public virtual DbSet<Sample_ASet> Sample_ASet { get; set; }
        public virtual DbSet<TuffAnalysisResultSet> TuffAnalysisResultSet { get; set; }
        public virtual DbSet<TuftSet> TuftSet { get; set; }
        public virtual DbSet<TuftTempSetSet> TuftTempSetSet { get; set; }
        public virtual DbSet<Models> ModelsSet { get; set; }
        public virtual DbSet<Datasets> DatasetsSet { get; set; }
        public virtual DbSet<ValidationDataset> ValidationDatasetSet { get; set; }
        public virtual DbSet<Vsample_ASet> Vsample_ASet { get; set; }
        public virtual DbSet<VtuftSet> VtuftSets { get; set; }
        public virtual DbSet<VbristleSet> VbristleSets { get; set; }
        public virtual DbSet<VimageSet> VimageSets { get; set; }
        public virtual DbSet<ValidationDatasets> ValidationDatasets { get; set; }
        public virtual DbSet<UserSystem> UserSystems { get; set; }
        public virtual DbSet<GeneralSettings> GeneralSettings { get; set; }
        public virtual DbSet<AI_Sample_log> AI_Sample_log { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Audit_Trail> Audit_Trail { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<QM_Spec> QM_Spec { get; set; }
        public virtual DbSet<QM_Status> QM_Status { get; set; }
        public virtual DbSet<SKU> SKUs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<C_Debug> C_Debug { get; set; }
        public virtual DbSet<CheckList> CheckLists { get; set; }
        public virtual DbSet<EquipmentType> EquipmentTypes { get; set; }
        public virtual DbSet<ImportData> ImportDatas { get; set; }
        public virtual DbSet<Sample_log> Sample_log { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<VW_SampleValues> VW_SampleValues { get; set; }
    
        [DbFunction("ColgateSkeltaEntities", "ngsfr_fn_S_Split_List")]
        public virtual IQueryable<ngsfr_fn_S_Split_List_Result> ngsfr_fn_S_Split_List(string @string)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ngsfr_fn_S_Split_List_Result>("[ColgateSkeltaEntities].[ngsfr_fn_S_Split_List](@string)", stringParameter);
        }         
    }
}
