//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportData
    {
        public int iID { get; set; }
        public Nullable<int> iProcessStatus { get; set; }
        public string iProcessID { get; set; }
        public string sSKU { get; set; }
        public string sDescription { get; set; }
        public string iArea_id { get; set; }
        public Nullable<int> iTest_id { get; set; }
        public string sTestDesc { get; set; }
        public double fUSL { get; set; }
        public double fLSL { get; set; }
        public double fUCL { get; set; }
        public double fLCL { get; set; }
        public double fUAL { get; set; }
        public double fLAL { get; set; }
        public double fTarget { get; set; }
        public string iAreaID { get; set; }
        public string sAreaDesc { get; set; }
        public string iEquipment_id { get; set; }
        public string sEquipmentDesc { get; set; }
        public string sCreated_by { get; set; }
        public System.DateTime dtCreated_at { get; set; }
    }
}
