//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Models
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Models()
        {
            this.Datasets = new HashSet<Datasets>();
            this.ValidationDatasets = new HashSet<ValidationDatasets>();
        }
    
        public int Id { get; set; }
        public double PerformanceType1 { get; set; }
        public string Status { get; set; }
        public double PerformanceType2 { get; set; }
        public double PerformanceType3 { get; set; }
        public double PerformanceNone { get; set; }
        public double PerformanceLocalization { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Datasets> Datasets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidationDatasets> ValidationDatasets { get; set; }
    }
}
