//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class QM_Spec
    {
        public int iID { get; set; }
        public int iTest_id { get; set; }
        public double fSpec_UpperLimit { get; set; }
        public double fSpec_LowerLimit { get; set; }
        public double fControl_UpperLimit { get; set; }
        public double fControl_LowerLimit { get; set; }
        public double fAccept_UpperLimit { get; set; }
        public double fAccept_LowerLimit { get; set; }
        public double fTarget { get; set; }
        public string sSpare { get; set; }
        public string sCreated_by { get; set; }
        public System.DateTime dtCreated_at { get; set; }
    }
}
