//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuffAnalysisResultSet
    {
        public int Id { get; set; }
        public string Position { get; set; }
        public int TotalBristlesFoundNN { get; set; }
        public int TotalBristleFoundManual { get; set; }
        public bool SelectedManual { get; set; }
        public string Probability { get; set; }
    
        public virtual AnalyzeSet AnalyzeSet { get; set; }
    }
}
