//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SampleValues
    {
        public int iID { get; set; }
        public int iStatus_id { get; set; }
        public Nullable<bool> bActive { get; set; }
        public int iShift { get; set; }
        public int iTest_id { get; set; }
        public string sDescription { get; set; }
        public string sSKU { get; set; }
        public string sEquipament { get; set; }
        public string sArea { get; set; }
        public string sBatchLote { get; set; }
        public string dtSample { get; set; }
        public double fResult { get; set; }
        public string sOperator { get; set; }
        public string sComments { get; set; }
        public string dtEditTime { get; set; }
    }
}
